server:
  port: 8080
  servlet:
    context-path: /services/be/auth-service

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: codemirror17@gmail.com
    password: olwjkegubzdcdwup
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



doc:
  api:
    path: /doc/api
    title: User API
    description: Documentation for the Auth API
    version: 1.0.0


jwt:
  signature: L3OaW5Jv7f9qT8U0pD7rYkJ9u3PxMfBcXlZAnKj2hFs=
  expiration: 3600000  # 1 hora
  refresh-expiration: 86400000  # 24 horas


