server:
  port: 8280
  forward-headers-strategy: framework

spring:
  application:
    name: API-GATEWAY
    restclient:
      user:
        url: http://20.63.88.120:8081/services/be/user-service/

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, *

      routes:
        - id: user-service
          uri: http://20.63.88.120:8081
          predicates:
            - Path=/services/be/user-service/**

        - id: code-service
          uri: http://20.63.88.120:8086
          predicates:
            - Path=/services/be/code-service/**

        - id: offer-service
          uri: http://20.63.88.120:8082
          predicates:
            - Path=/services/be/offer-service/**
        - id: interview-service
          uri: http://20.63.88.120:8083
          predicates:
            - Path=/services/be/interview-service/**
        - id: audio-service
          uri: http://20.63.88.120:8084
          predicates:
            - Path=/services/be/stream-service/**
        - id: stream-ws
          uri: ws://20.63.88.120:8084
          predicates:
            - Path=/services/be/stream-service/**

  mail:
    host: smtp.gmail.com
    port: 587
    username: codemirror17@gmail.com
    password: olwjkegubzdcdwup
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

doc:
  api:
    path: /doc/api
    title: auth API
    description: Documentation for the Auth API
    version: 1.0.0


jwt:
  signature: gKZpDd8M3vXt7XLGlbZG2dFv1F5LSK+QAcX9A4qVq2aLbEEMww6slvENxwX+9Q27FO3EtzNbdRYJ7xKAlv3dMw==
  expiration: 3600000  # 1 hora
  refresh-expiration: 86400000  # 24 horas

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    io.netty: DEBUG
    reactor.netty: DEBUG
    reactor.netty.channel: TRACE
    reactor.netty.http.client: TRACE
    reactor.netty.transport: TRACE
