server:
  port: 8280
  forward-headers-strategy: framework  # Reconoce headers como X-Forwarded-Proto en Azure

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - AddResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, *

      routes:
        - id: user-service
          uri: http://20.63.88.120:8080
          predicates:
            - Path=/services/be/user-service/**
        - id: offer-service
          uri: http://20.63.88.120:8080
          predicates:
            - Path=/services/be/offer-service/**
        - id: interview-service
          uri: http://20.63.88.120:8083
          predicates:
            - Path=/services/be/interview-service/**
        - id: audio-service
          uri: http://20.63.88.120:8084
          predicates:
            - Path=/services/be/stream-service/**
        - id: stream-ws
          uri: ws://20.63.88.120:8084
          predicates:
            - Path=/services/be/stream-service/**

  mail:
    host: smtp.gmail.com
    port: 587
    username: codemirror17@gmail.com
    password: olwjkegubzdcdwup
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /services/be/user-service/v3/api-docs
      - name: offer-service
        url: /services/be/offer-service/v3/api-docs
      - name: interview-service
        url: /services/be/interview-service/v3/api-docs

jwt:
  signature: L3OaW5Jv7f9qT8U0pD7rYkJ9u3PxMfBcXlZAnKj2hFs=
  expiration: 3600000  # 1 hora
  refresh-expiration: 86400000  # 24 horas

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    io.netty: DEBUG
    reactor.netty: DEBUG
    reactor.netty.channel: TRACE
    reactor.netty.http.client: TRACE
    reactor.netty.transport: TRACE
