version: '3.8'

services:
  auth:
    image: mysql:8.0
    container_name: auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    ports:
      - "3306:3306"
    volumes:
      - auth_data:/var/lib/mysql

volumes:
  auth_data:
